"""Expenses_type_enum

Revision ID: 63fa5790edce
Revises: cea9c4836c6f
Create Date: 2025-07-10 22:52:37.175171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63fa5790edce'
down_revision: Union[str, None] = 'cea9c4836c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PURCHASE', 'PARTS', 'WHEELS', 'REPAIR', 'PAINT', 'FUEL', 'DETAILING', 'ADS', 'OTHER', name='expensetype').create(op.get_bind())
    op.add_column('expenses', sa.Column('type', postgresql.ENUM('PURCHASE', 'PARTS', 'WHEELS', 'REPAIR', 'PAINT', 'FUEL', 'DETAILING', 'ADS', 'OTHER', name='expensetype', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'type')
    sa.Enum('PURCHASE', 'PARTS', 'WHEELS', 'REPAIR', 'PAINT', 'FUEL', 'DETAILING', 'ADS', 'OTHER', name='expensetype').drop(op.get_bind())
    # ### end Alembic commands ###
