"""Removed_price_purchased_from_Cars

Revision ID: 99377c061444
Revises: 63fa5790edce
Create Date: 2025-07-10 23:19:44.455435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99377c061444'
down_revision: Union[str, None] = '63fa5790edce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'price_purchased')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('price_purchased', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
