"""exp_add_used_uid

Revision ID: 9f4f5a275e37
Revises: f597cbebfe4a
Create Date: 2025-06-22 13:39:44.539547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f4f5a275e37'
down_revision: Union[str, None] = 'f597cbebfe4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_uid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_expenses_user_uid'), 'expenses', ['user_uid'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_uid'), table_name='expenses')
    op.drop_column('expenses', 'user_uid')
    # ### end Alembic commands ###
