"""user_car_relationship

Revision ID: a042276bcd19
Revises: 89a438a8ec59
Create Date: 2025-06-03 10:38:52.799219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a042276bcd19'
down_revision: Union[str, None] = '89a438a8ec59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('owner_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cars_owner_uid'), 'cars', ['owner_uid'], unique=False)
    op.create_foreign_key(None, 'cars', 'users', ['owner_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_index(op.f('ix_cars_owner_uid'), table_name='cars')
    op.drop_column('cars', 'owner_uid')
    # ### end Alembic commands ###
