"""add_user_roles_nullable

Revision ID: a584c3194066
Revises: a042276bcd19
Create Date: 2025-06-11 13:18:38.726651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a584c3194066'
down_revision: Union[str, None] = 'a042276bcd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ADMIN', name='userrole').create(op.get_bind())
    op.drop_constraint('cars_owner_uid_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['owner_uid'], ['uid'], ondelete='CASCADE')
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='userrole', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_owner_uid_fkey', 'cars', 'users', ['owner_uid'], ['uid'])
    sa.Enum('USER', 'ADMIN', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
