"""many_owners

Revision ID: cea9c4836c6f
Revises: 9f4f5a275e37
Create Date: 2025-07-09 10:33:19.435490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cea9c4836c6f'
down_revision: Union[str, None] = '9f4f5a275e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_user_link',
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('car_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['car_uid'], ['cars.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'car_uid')
    )
    op.add_column('cars', sa.Column('primary_owner_uid', sa.UUID(), nullable=True))
    op.drop_index('ix_cars_owner_uid', table_name='cars')
    op.create_index(op.f('ix_cars_primary_owner_uid'), 'cars', ['primary_owner_uid'], unique=False)
    op.drop_constraint('cars_owner_uid_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['primary_owner_uid'], ['uid'], ondelete='CASCADE')
    op.drop_column('cars', 'owner_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('owner_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_owner_uid_fkey', 'cars', 'users', ['owner_uid'], ['uid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cars_primary_owner_uid'), table_name='cars')
    op.create_index('ix_cars_owner_uid', 'cars', ['owner_uid'], unique=False)
    op.drop_column('cars', 'primary_owner_uid')
    op.drop_table('car_user_link')
    # ### end Alembic commands ###
