"""expenses_cascade_del

Revision ID: f597cbebfe4a
Revises: a584c3194066
Create Date: 2025-06-11 13:23:49.987921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f597cbebfe4a'
down_revision: Union[str, None] = 'a584c3194066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expenses_car_uid'), 'expenses', ['car_uid'], unique=False)
    op.drop_constraint('expenses_car_uid_fkey', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'cars', ['car_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_car_uid_fkey', 'expenses', 'cars', ['car_uid'], ['uid'])
    op.drop_index(op.f('ix_expenses_car_uid'), table_name='expenses')
    # ### end Alembic commands ###
